### PR TITLE
Fix for #738

### PR DESCRIPTION
**Pull request by akshay-raj-dhamija**
This fixes the variable name `EIGEN3_INCLUDE_DIRS` to `EIGEN3_INCLUDE_DIR` in the cmake dependencies as mentioned in issue https://github.com/caffe2/caffe2/issues/738
Ref: https://cmake-basis.github.io/apidoc/latest/FindEigen3_8cmake_source.html

### CODE REVIEW

**Comment by akshay-raj-dhamija** [comment]
@hgaiser @lukeyeager Could you please review this small change for a merger.
Thanks!

**Comment by hgaiser** [comment]
This error seems weird to me as the cmake that is provided by Eigen should set `EIGEN3_INCLUDE_DIRS` (https://bitbucket.org/eigen/eigen/src/8d1ccfd9c5a0bf1a662bd0fe35858f4e527d2bac/cmake/Eigen3Config.cmake.in?at=default&fileviewer=file-view-default). I couldn't find a cmake module in the cmake GitHub repository. What is that cmake-basis you are referencing? If it was using the Eigen's version of it's cmake module it would work fine. Can you try to find out why it is not using that cmake module? Is it even available?

**Comment by akshay-raj-dhamija** [comment]
Thanks for your prompt response.
It appears that though the [current cmake](https://bitbucket.org/eigen/eigen/src/8d1ccfd9c5a0bf1a662bd0fe35858f4e527d2bac/cmake/Eigen3Config.cmake.in?at=default&fileviewer=file-view-default#Eigen3Config.cmake.in-15
) from eigen sets `EIGEN3_INCLUDE_DIRS`, it isn't consistent with a [Previous Version](https://bitbucket.org/eigen/eigen/src/1db6cf71f62897825a643f5faca8a54adc90b41d/cmake/Eigen3Config.cmake.in?fileviewer=file-view-default#Eigen3Config.cmake.in-22) of eigen.
But, it also appears that `EIGEN3_INCLUDE_DIR` hasn't changed between these versions. To support previous versions of eigen it might be better to use `EIGEN3_INCLUDE_DIR`.

**Comment by hgaiser** [comment]
The only difference between the two cmake files you linked is the name of the internal variable they use to substitute when compiling the cmake file (is it called compiling? Or template substitution?). The variable `EIGEN3_INCLUDE_DIRS` appears to exist since the `EIGEN3_*` variables were added (https://bitbucket.org/eigen/eigen/diff/cmake/Eigen3Config.cmake.in?diff2=21fbeccc596f&at=vladimir_ch/bug-796-fix-eigen3config.cmake). I still believe the real issue is that your system is not finding the cmake provided by Eigen.

**Comment by pietern** [comment]
Thanks @hgaiser for investigating. Also checked /usr/lib/cmake/eigen3 (on Ubuntu) and confirmed it sets both, so we can stick to EIGEN_INCLUDE_DIRS.

**Comment by gemarcano** [comment]
[Upstream's FindEigen3.cmake](https://bitbucket.org/eigen/eigen/src/2784ec4bdf50a92acfd0dd2396a81ffc3e1b993a/cmake/FindEigen3.cmake?at=default&fileviewer=file-view-default) only defines `EIGEN_INCLUDE_DIR`... makes me wonder what version the Ubuntu repositories are using, but it isn't latest (unless Ubuntu is patching something, this means in the future a future release is going to break this).

EDIT: I see that the file you're looking at is Eigen3Config.cmake, which does set that secondary variable, even upstream. This means I'm running into another problem. Disregard this comment.

**Comment by pietern** [comment]
This was also the case on CentOS. I updated this to use EIGEN3_INCLUDE_DIR (singular) in #1505.

**Pull request closed without merging**
