### PR TITLE
[wip] Cmake modernization

### PR DESCRIPTION
**Pull request by Yangqing**
Not ready for merge yet. Starting a PR to kick off contbuild test.

### CODE REVIEW

**Comment by Yangqing** [comment]
@caffe2bot test this please

**Comment by Yangqing** [comment]
@caffe2bot retest this please (jenkins had a hiccup)

**Comment by Yangqing** [comment]
@caffe2bot retest this please (jenkins hiccup continues)

**Review by pjh5 — APPROVED** [review]

**Comment by pjh5** [comment]
You should ignore those broken conda builds, they're not working yet :(

**Comment by Yangqing** [comment]
Thanks @pjh5 ! Landing.

**Pull request merged**
