### PR TITLE
Run more hypothesis tests in OSS CI

### PR DESCRIPTION
**Pull request by dzhulgakov**
replicate internal CI behavior. Otherwise it's easy to miss some issues

### CODE REVIEW

**Review by bddppq — APPROVED** [review]

**Comment by dzhulgakov** [comment]
oh wow, looks like we have quite a few flaky tests. Will try to look into it later

**Comment by bddppq** [comment]
@dzhulgakov I randomly clicked some of the failed runs, and see all of them are timing out. Right now in the CI system we are setting a 30min timeout on each job.

**Comment by Yangqing** [comment]
@caffe2bot retest this please.

**Comment by orionr** [comment]
@caffe2bot retest this please

**Pull request closed without merging**
