### PR TITLE
Mark in-place GPU dropout as broken, add test

### PR DESCRIPTION
**Pull request by lukeyeager**
I'll let y'all decide how you want to fix this (probably need a persistent curand buffer). Here's a test to verify the fix.

### CODE REVIEW

**Comment by pietern** [comment]
LGTM... @Yangqing?

**Comment by lukeyeager** [comment]
I'm happy to go ahead and implement the fix as well if you'd like. I can see several ways to handle it:

* Allocate/deallocate a new GPU buffer each time
* Allocate a GPU buffer once, and reallocating when the size changes
* Add a new output for the op which nobody would ever use
* Change the type of the mask output to float instead of bool (can still set to 1/0 after curand is done with it)

**Comment by lukeyeager** [comment]
Ping. This is a pretty brutal silent failure right now.

**Comment by akyrola** [comment]
Thanks for noticing this. Of course happy to get a fix for this :)

**Pull request closed without merging**
