### PR TITLE
Re-enable event_test/event_gpu_test

### PR DESCRIPTION
**Pull request by pietern**
Disabled when configuring Jenkins to get a run where tests pass.

### CODE REVIEW

**Comment by pietern** [comment]
event_gpu_test hangs:

```
(gdb) bt
#0  0x00007fe380936404 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fe3806d44dc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from target:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fe388634eaa in caffe2::EventFinishCPU(caffe2::Event const*) () from target:/usr/local/caffe2/lib/libcaffe2.so
#3  0x000000000041711c in caffe2::EventCUDATest_EventBasics_Test::TestBody() ()
```

**Comment by pietern** [comment]
@Yangqing Can you take a look at this? You wrote this test back in August.

**Comment by pietern** [comment]
Backtrace from debug build:

```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f2b06e694dc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f2b0f076aca in caffe2::EventFinishCPU (event=<optimized out>) at /var/lib/jenkins/workspace/caffe2/core/event.cc:69
#3  0x0000000000443081 in Wait (context=0x7ffea4bd0510, waiter_type=0, this=0x7ffea4bd05a0) at /var/lib/jenkins/workspace/caffe2/core/event.h:93
#4  WaitEvent (ev=..., this=0x7ffea4bd0510) at /var/lib/jenkins/workspace/caffe2/core/context.h:96
#5  caffe2::EventCUDATest_EventBasics_Test::TestBody (this=<optimized out>) at /var/lib/jenkins/workspace/caffe2/core/event_gpu_test.cc:39
```

**Comment by Yangqing** [comment]
@ilia-cher do you mind taking a look?

**Comment by Yangqing** [comment]
My bad, PR already at #1452

**Comment by pietern** [comment]
Yep, fix in #1452

**Pull request closed without merging**
