### PR TITLE
GRU cell: add linear_before_reset boolean parameter

### PR DESCRIPTION
**Pull request by anderspapitto**
This matches the semantics of cudnn (and others, like pytorch)

### CODE REVIEW

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by pietern** [comment]
@anderspapitto The pooling tests are known to fail, but the others look related.

**Comment by pietern** [comment]
Thanks! The failures are all unrelated.

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by pietern** [comment]
@anderspapitto Still one flaky GRU test, see https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-gcc5-ubuntu16.04-test/279/

**Comment by anderspapitto** [comment]
I believe this is ready to land - I've fixed my tests, and the failures I see look unrelated (here and on phabricator)

**Comment by pietern** [comment]
@anderspapitto Yep the failures here are not related to your change.

**Comment by anderspapitto** [comment]
landed

**Pull request closed without merging**
