### PR TITLE
disable travis test for dpm test

### PR DESCRIPTION
**Pull request by Yangqing**
After this, we should have test going back to all green.

### CODE REVIEW

**Comment by Yangqing** [comment]
@andrewwdye feel free to choose to land this first or to wait for the once and for all solution :)

**Review by harouwu — APPROVED** [review]
Looks like Travis is complaining about a different issue. Please rebase and test it again.
This diff LGTM

**Comment by Yangqing** [comment]
Closing since @andrewwdye is working on a permanent fix.

**Comment by Yangqing** [comment]
Actually, in light of #1093 let's merge this before a permanent solution can be dealt with.

**Pull request closed without merging**
