### PR TITLE
Pin libnccl2 to version 2.1.2

### PR DESCRIPTION
**Pull request by pietern**
Version 2.1.4 exports C++ symbols that it shouldn't, which causes a
mismatch between raised exceptions and expected exceptions.

Pin this to 2.1.2 until this is solved and NVIDIA releases a new version.

cc @slayton58

### CODE REVIEW

**Comment by pietern** [comment]
Images building in https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/69/

**Comment by Yangqing** [comment]
Note that it's expected to break cuda9.1 docker images, due to 2.1.2+cuda9.1 not available:

http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/

Post 2.1.4 bugfix we should be back fine.

**Comment by Yangqing** [comment]
FWIW #2038 triggered a new docker build. Just FYI.

**Comment by Yangqing** [comment]
New image building at https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/74/

**Comment by Yangqing** [comment]
Successfully rebuilt docker images at https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/76/ . Merging.

**Review by Yangqing — APPROVED** [review]

**Pull request merged**
