### PR TITLE
strip some python dependencies

### PR DESCRIPTION
**Pull request by bddppq**
those are only used in non-core part

### CODE REVIEW

**Review by orionr — APPROVED** [review]

**Review by houseroad — COMMENTED** [review]
No setuptools !?

**Comment by bddppq** [comment]
@houseroad it's not counted as install dependencies of caffe2, without it you won't even be able to run our setup.py :-)

**Review by pjh5 — COMMENTED** [review]
You can axe matplotlib too

**Comment by houseroad** [comment]
I would like to include setuptools... to me, the experience of using setup.py is way better than pure cmake/make installation.

I remember half a year ago, I had suffered from cmake/make installation... with support of setuptools, it was so easy to install caffe2, and even my skin got better. :-)

**Comment by bddppq** [comment]
@houseroad it's unrelated to setup.py vs. cmake. my point is you don't need to specify setuptools as dependencies of caffe2 in setup.py, because in order to run our setup.py you must already have setuptools installed.

**Comment by houseroad** [comment]
@bddppq cool, I got your point, thanks!

**Review by houseroad — APPROVED** [review]

**Pull request merged**
