### PR TITLE
Enable OpenGL build

### PR DESCRIPTION
**Pull request by freedomtan**
with these small patches, we can build
arm64-v8a with clang: e.g.,  `scripts/build_android.sh -DBUILD_BINARY=ON -DBUILD_TEST=ON -DUSE_MOBILE_OPENGL=ON -DBUILD_OBSERVERS=ON -DANDROID_TOOLCHAIN=clang -DUSE_ARM64=ON` 
armeabi-v7a with gcc: e.g., `scripts/build_android.sh -DBUILD_BINARY=ON  -DBUILD_TEST=ON -DUSE_MOBILE_OPENGL=ON -DBUILD_OBSERVERS=ON`

And run `caffe2_benchmark` on Android device with something like `./caffe2_benchmark --backend=opengl ...`

### CODE REVIEW

**Comment by freedomtan** [comment]
rebased and updated to resolve conflicts after the integration of ARM Compute Library (#2015)

**Comment by freedomtan** [comment]
updated after recent cmake refactoring. @sf-wind: Does this look good?
```
@@ -77,7 +77,7 @@ if(USE_NNPACK)
   endif()
 endif()
 
-if(USE_OBSERVERS)
+if(USE_OBSERVERS OR BUILD_OBSERVERS)
   list(APPEND Caffe2_DEPENDENCY_LIBS Caffe2_CPU_OBSERVER)
 endif()
```

**Comment by freedomtan** [comment]
rebased and updated to resolve conflicts again

**Comment by orionr** [comment]
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

**Pull request closed without merging**
