### PR TITLE
Import the FindCUDA module from CMake

### LINKED ISSUE #1397: Failed to build caffe2 on Centos
Hi, I am building caffe2 from source, per instructions here https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud, and it has problem compiling gloo related stuff. Here is the output:

liangluo@n37:~/caffe2/build$ make
[ 14%] Built target nccl_external
[ 14%] Built target pthreadpool
[ 14%] Built target nnpack_reference_layers
[ 14%] Built target nnpack
[ 14%] Built target gmock_main
[ 14%] Built target gmock
[ 14%] Built target gtest
[ 14%] Built target gtest_main
[ 14%] Built target benchmark
[ 14%] Built target gloo
[ 14%] Building NVCC (Device) object third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at gloo_cuda_generated_nccl.cu.o.Release.cmake:203 (message):
  Error generating
  /xxxxx/home/liangluo/caffe2/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/./gloo_cuda_generated_nccl.cu.o

make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o] Error 1
make[1]: *** [third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/all] Error 2
make: *** [all] Error 2

I'm using CUDA 8.

Any suggestion? Any more information required?

Thanks!

### PR DESCRIPTION
**Pull request by pietern**
This addresses a problem where a generator expression for include
directories was passed to NVCC, where the generator expression itself
was prefixed by -I. As the NNPACK include directory generator
expression expands to multiple directories, the second and later ones
were not prefixed by -I, causing nvcc to return an error.

This was first fixed in CMake 3.7 (see Kitware/CMake@7ded655f).

To fix this, we can import and track FindCUDA from CMake upstream.

The most recent change to these files is Kitware/CMake@21806e6f.

This fixes #1397.

### CODE REVIEW

**Comment by pietern** [comment]
Still have to double check that this doesn't break for ex Windows.

PyTorch also uses upstream FindCUDA (see [pytorch/cmake/FindCUDA](https://github.com/pytorch/pytorch/tree/master/cmake/FindCUDA)) and that version was modified after the initial commit. Perhaps there are some modifications we need to port here. @Yangqing @soumith Do you recall any specifics about these mods?

**Comment by pietern** [comment]
This doesn't work with CMake 2.8.12. Fixing that first.

**Comment by soumith** [comment]
i cant recall any specific changes wrt Windows and pytorch's FindCUDA. I know a bunch of changes were made by folks over the years.

**Comment by Yangqing** [comment]
FYI - the windows 2017 fix is something like this: https://github.com/Kitware/fletch/pull/296/commits/bb29b63bf82914c5b09cb5e32dd69c3a56624c5a

**Comment by Yangqing** [comment]
Should have been fixed by #1727 now.

**Comment by pietern** [comment]
@Yangqing This doesn't fix the CentOS path -- only the MSVC path.

**Comment by pietern** [comment]
Keeping this open even though this is not in a mergable state.

**Comment by orionr** [comment]
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

**Pull request closed without merging**
