### PR TITLE
Fix #1355: do not expose Eigen header includes

### LINKED ISSUE #1355: Eigen headers still #included with OpenBLAS
I compiled commit 55b3b14101fc75fc3564ef2887b1b689039298a3 from source with `-DBLAS=OpenBLAS` and without CUDA. Yet, some headers still `#include` Eigen headers causing a compilation error when you want to use the C++ API. Since I use OpenBLAS, I expect that there is *no* Eigen dependency when using the Caffe2 headers.

Minimum working example:
```c++
#include <caffe2/core/predictor.h>
int main() {}
```
Error message:
```
christoph:/tmp$ g++ mwe.cpp -I/tmp/caffe2.x86_64-linux-gnu/include -c -std=c++11
In file included from /tmp/caffe2.x86_64-linux-gnu/include/caffe2/core/context.h:30:0,
                 from /tmp/caffe2.x86_64-linux-gnu/include/caffe2/core/tensor.h:30,
                 from /tmp/caffe2.x86_64-linux-gnu/include/caffe2/core/net.h:34,
                 from /tmp/caffe2.x86_64-linux-gnu/include/caffe2/core/predictor.h:19,
                 from mwe.cpp:1:
/tmp/caffe2.x86_64-linux-gnu/include/caffe2/utils/math.h:36:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
```
[Line 36 in `caffe2/utils/math.h`](https://github.com/caffe2/caffe2/blob/55b3b14101fc75fc3564ef2887b1b689039298a3/caffe2/utils/math.h#L36)

### PR DESCRIPTION
**Pull request by christoph-conrads**
Exposing includes of Eigen headers in Caffe2 headers leads to compiler
errors in C++ code using Caffe2 if Eigen is _not_ the BLAS back-end.

The PR is based on PR #1361.

### CODE REVIEW

**Comment by Yangqing** [comment]
Thanks so much! I never got time to finish that one.

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by pietern** [comment]
@christoph-conrads The build failure looks related to the math.h change, could you take a look?

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by pietern** [comment]
@caffe2bot test this please

**Comment by Yangqing** [comment]
@christoph-conrads thanks for the fixes!

Quick update from my side: I am importing and fixing a few downstream build failures that we had in production code that rely on some of these caffe2 headers. Once that passes build I'll merge. Thanks again!

**Comment by pietern** [comment]
And I'm adding you to the whitelist... ;)

@caffe2bot test this please

**Comment by christoph-conrads** [comment]
@pietern Hi, which whitelist? For the the build bot? It seems to be building Caffe2 whenever I git-push.

**Comment by christoph-conrads** [comment]
I fail to see what went wrong in [job #2897.2](https://travis-ci.org/caffe2/caffe2/jobs/302763642) because there is no error message, all tests pass, and the installation finishes.

**Comment by pietern** [comment]
We have used Travis for a while but added Jenkins that runs GPU tests recently. This is every build prefixed with "pr/*" in the list of checks here. The most recent one looks like a false negative, so let me retrigger.

**Comment by pietern** [comment]
@caffe2bot retest this please

**Comment by pietern** [comment]
The caffe2-linux-xenial-mkl failure is a core dump in an unrelated test. Compilation is OK.

**Comment by Yangqing** [comment]
I am approaching the end of the internal header fixes for dependent projects. Verification runs a bit slow mainly because it hits many parts of our use cases, so quite a few tests are being done. Expect this to merge by today - thanks so much again!

**Comment by Yangqing** [comment]
Update - this is now landed in https://github.com/caffe2/caffe2/commit/018e952a160542d35ebfc6b2377f5088ed197cb5 . Thanks so much @christoph-conrads for the fix! I had to manually apply it mainly because it got caught in between our code refactoring across platforms, and quite a few dependent libraries that use caffe2 has to be updated jointly.

**Pull request closed without merging**
