### PR TITLE
wip: cuda targets

### PR DESCRIPTION
**Pull request by Yangqing**
(this is in order to modernize the cuda targets and allow caffe2_gpu library to be relocatable with cmake. Not sure if this builds yet. my local mac passes cmake configuration but not sure about the rest.)

### CODE REVIEW

**Review by pjh5 — APPROVED** [review]
Do you know if we should ever also set compiler flags like this example
"
  set_target_properties(Foo::Foo PROPERTIES
    INTERFACE_COMPILE_OPTIONS "${PC_Foo_CFLAGS_OTHER}"
    INTERFACE_INCLUDE_DIRECTORIES "${Foo_INCLUDE_DIR}"
  )
" on https://cmake.org/cmake/help/v3.5/manual/cmake-developer.7.html#find-modules ?

**Comment by Yangqing** [comment]
@pjh5 yep. For compiler flags that should be used in host compilers, we should totally set so. In this case for the NVCC flags though, it is added to nvcc compilers so it needs to be custom.

**Comment by Yangqing** [comment]
I am almost sure that the test errors are not due to this change (it is purely CMake), but I'll hold on till they get resolved first.

**Comment by pjh5** [comment]
@Yangqing these test failures have come up sporadically for a while now. I suggest you do not wait for them

**Comment by pietern** [comment]
`blobs_queue_db_test.py::BlobsQueueDBTest::test_create_blobs_queue_db_string` is hanging for the CUDA builds, but this has been the case on master for a while... This should be fixed ASAP but is unrelated to your changes here.

**Comment by Yangqing** [comment]
Sounds great, thanks guys - landing.

**Comment by pjh5** [comment]
Sweet

**Pull request merged**
