### PR TITLE
Update Caffe2 from Facebook

### PR DESCRIPTION
**Pull request by orionr**
Syncing internal changes

### CODE REVIEW

**Review by Yangqing — APPROVED** [review]
Stamping.

**Comment by yinghai** [comment]
Looks like legit code error:
```
17:34:37 /var/lib/jenkins/workspace/caffe2/operators/gather_ranges_to_dense_op.h:123:53: note: candidate: caffe2::GatherRangesToDenseOp<Context>::DoRunWithType()::<lambda(const int&, const int&)> [with Index = long int; Context = caffe2::CPUContext]
17:34:37                [](const auto& left, const auto& right) {
17:34:37                                                      ^
17:34:37 /var/lib/jenkins/workspace/caffe2/operators/gather_ranges_to_dense_op.h:123:53: note:   no known conversion for argument 1 from 'std::pair<long int, const char*>' to 'const int&'
```

**Comment by orionr** [comment]
Looks like we now have a build failure:

```
caffe2/CMakeFiles/caffe2_gpu.dir/operators/caffe2_gpu_generated_locally_connected_op_cudaconvnet.cu.o
15:10:28 In file included from /var/lib/jenkins/workspace/caffe2/operators/locally_connected_op_cudaconvnet.cu:21:0:
15:10:28 /var/lib/jenkins/workspace/caffe2/contrib/cuda-convnet2/cudaconv3/include/cudaconv2.cuh:20:84: fatal error: helper_cuda.h: No such file or directory
```
@Yangqing any thoughts? Thanks.

**Comment by orionr** [comment]
Backing out that last commit in the stack and waiting for tests to pass. Once they do this is coming in.

**Pull request merged**
