### PR TITLE
Make caffe2 handle out of bounds values correctly

### PR DESCRIPTION
**Pull request by smessmer**
according to the new onnx standard in https://github.com/onnx/onnx/pull/513

### CODE REVIEW

**Comment by bddppq** [comment]
@caffe2bot test this please

**Comment by smessmer** [comment]
@caffe2bot test this please

**Comment by houseroad** [comment]
@caffe2bot test this please

**Comment by houseroad** [comment]
@caffe2bot test this please

**Review by houseroad — APPROVED** [review]
LGTM

**Comment by bddppq** [comment]
landing this to unbreak onnx-caffe2 CI failure

**Pull request closed without merging**
