### PR TITLE
[caffe2] Fix contrib/script build

### PR DESCRIPTION
**Pull request by dzhulgakov**
Fixes a missing line in https://github.com/caffe2/caffe2/commit/ff2c9735477e4d5076da4ddfc964eb0fd3c360bf

@zdevito @jamesr66a

### CODE REVIEW

**Comment by jamesr66a** [comment]
Is this not covered in FB contbuild?


On Nov 29, 2017, at 10:49 PM, Dmytro Dzhulgakov <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixes a missing line in ff2c973<https://github.com/caffe2/caffe2/commit/ff2c9735477e4d5076da4ddfc964eb0fd3c360bf>

@zdevito<https://github.com/zdevito> @jamesr66a<https://github.com/jamesr66a>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/caffe2/caffe2/pull/1540

Commit Summary

  *   [caffe2] Fix contrib/script build

File Changes

  *   M caffe2/contrib/CMakeLists.txt<https://github.com/caffe2/caffe2/pull/1540/files#diff-0> (1)

Patch Links:

  *   https://github.com/caffe2/caffe2/pull/1540.patch
  *   https://github.com/caffe2/caffe2/pull/1540.diff

**Comment by outkasst** [comment]
I just downloaded latest caffe2, ubuntu 16.. installed it successfully.. Still see this error:WARNING:root:Debug message: /home/outkasst/caffe2p3home/caffe2/build/caffe2/python/caffe2_pybind11_state_gpu.so: und
efined symbol: _Py_ZeroStruct
CRITICAL:root:Cannot load caffe2.python. Error: /home/outkasst/caffe2p3home/caffe2/build/caffe2/python/caffe2_pybind
11_state.so: undefined symbol: _Py_ZeroStruct

I am a noob in this, but looks like the above fix in the thread fixes it.. How do i get the fixed version? Or any idea on how to fix this?

thx
Outkasst

**Comment by bddppq** [comment]
@outkasst Your issue is different. It's very likely you have built caffe2 with python2 and then later import it into python3.

**Comment by outkasst** [comment]
@bddppq , hi, how to resolve this issue? I am installing caffe2 inside a virtualenv.. with python3(3.5)..

thx

**Comment by ChampagneLee** [comment]
Hi @bddppq , I have successfully installed the latest Caffe2, but see this error:

```
$cd caffe2/build/
$python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named 'caffe2.python.caffe2_pybind11_state_gpu'
CRITICAL:root:Cannot load caffe2.python. Error: dlopen(/Users/xiangbinli/caffe2/build/caffe2/python/caffe2_pybind11_state.so, 10): Symbol not found: _PyCObject_Type
  Referenced from: /Users/xiangbinli/caffe2/build/caffe2/python/caffe2_pybind11_state.so
  Expected in: flat namespace
 in /Users/xiangbinli/caffe2/build/caffe2/python/caffe2_pybind11_state.so
```


My environment is:
Python 3.6.0
conda 4.4.8
MacOS High Sierra.

Does the wrong version of python cause that? Thanks a lot!

**Comment by obendidi** [comment]
Hi , I get the same error as @outkasst , but only when running on a jupyter notebook (on a script it works fine ) when tring to import caffe.python :` from caffe2.python import core, workspace`
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /usr/local/caffe2/python/caffe2_pybind11_state_gpu.so: undefined symbol: _Py_ZeroStruct
CRITICAL:root:Cannot load caffe2.python. Error: /usr/local/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _Py_ZeroStruct
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1


/home/sterblue/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**Pull request closed without merging**
