### PR TITLE
Allow the spatial batch norm operator to be computed in place

### PR DESCRIPTION
**Pull request by milewis1**

### CODE REVIEW

**Comment by salexspb** [comment]
should this also be reflected in the op tests? (for both order cases).

**Comment by milewis1** [comment]
Yes it should. That was next in my plan, but there was so little interest I
never followed up. I can certainly update it though.

**Comment by salexspb** [comment]
It just feels a little bit unsafe otherwise :) The code of the op has to be written in a curtain way for in place to work. Have you verified that it is correct?

**Comment by milewis1** [comment]
It is. However, I did check the operator and have been using it successfully in my models. However, since I'm no longer using Caffe2 and there hasn't been any interest in the SpatialBN work. I'm going to close out this PR.

**Comment by danielhauagge** [comment]
I'm very interested in this and could help. To get this merged, what would be the next steps?

**Comment by milewis1** [comment]
When I first made the change I check the operator and made sure it could
work in place. I think the real thing needed would be getting tests
written.

**Pull request closed without merging**
