### PR TITLE
Skip Cast ONNX backend test, which is not supported in Float16 case

### PR DESCRIPTION
**Pull request by houseroad**
Float16 casting is not supported yet.

### CODE REVIEW

**Comment by houseroad** [comment]
@caffe2bot retest this please

**Comment by bddppq** [comment]
Maybe only skip the fp16 test cases?

**Comment by Maratyszcza** [comment]
@houseroad @bddppq BTW, why is Cast not supported for FP16?

**Comment by houseroad** [comment]
@Maratyszcza will check and fix the cast in another PR with @zem7

**Review by bddppq — APPROVED** [review]

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@caffe2bot retest this please

**Comment by Yangqing** [comment]
@caffe2bot retest this please

**Pull request merged**
