### PR TITLE
Removed special handling for onnx sqrt

### PR DESCRIPTION
**Pull request by jspisak**

### CODE REVIEW

**Comment by houseroad** [comment]
@caffe2bot test this please

**Comment by yinghai** [comment]
@jspisak `sqrt` now doesn't require special treatment?

**Review by yinghai — COMMENTED** [review]
@jspisak sqrt now doesn't require special treatment?

**Comment by houseroad** [comment]
https://github.com/caffe2/caffe2/blob/master/caffe2/operators/sqrt_op.cc

@yinghai yeah, we have it now :-) Thanks to @jspisak's great work!

**Comment by houseroad** [comment]
@caffe2bot retest this please

**Comment by houseroad** [comment]
@caffe2bot retest this please

**Review by houseroad — APPROVED** [review]
Great, thanks!

**Pull request merged**
