### PR TITLE
Patch cuda-convnet2 from internal Facebook changes.

### PR DESCRIPTION
**Pull request by orionr**
* Unfortunately this needs to be manually monkey patched.
* This should get it so GitHub and fbcode versions match.

### CODE REVIEW

**Comment by orionr** [comment]
@caffe2bot retest this please

**Review by xiaomengy — APPROVED** [review]

**Comment by orionr** [comment]
@caffe2bot retest this please

**Comment by orionr** [comment]
@caffe2bot retest this please

**Comment by orionr** [comment]
@BIT-silence is going to take this one over and remove the cuda-convnet2 python code since it isn't python3 friendly.

**Comment by xiaomengy** [comment]
@caffe2bot retest this please

**Comment by orionr** [comment]
Okay - bringing this in even though conda builds fail, since @pjh5 will be working on those separately. Thanks all.

**Pull request merged**
