### PR TITLE
Use protoc path to figure out its install prefix 

### PR DESCRIPTION
**Pull request by pietern**
[x] Have to rebase
[x] Have to ensure this works on macOS + Anaconda

### CODE REVIEW

**Review by pjh5 — APPROVED** [review]
LGTM! We can do it for darwin too. I could look into it if you want

**Comment by pietern** [comment]
This is now good to go. @Yangqing can you take a look as well to see if all looks good?

After merging this I also want to change the CUSTOM_PROTOBUF variable to indicate that it's intended to be used for cross compilation and nothing else.

**Comment by pietern** [comment]
Removed the helper script and now use get_filename_component to figure out the path.

It's probably safe to assume that we can find the libraries in PREFIX/lib if protoc is installed in PREFIX/bin.

No need to query the RPATH.

**Comment by gokceneraslan** [comment]
`protoc` command cannot find libprotobuf.so when I compile bundled protobuf from caffe within a conda environment.

**Pull request closed without merging**
