### PR TITLE
Changes done internally at Facebook

### PR DESCRIPTION
**Pull request by orionr**
Bringing in changes as separate commits now so we can isolate test errors.

### CODE REVIEW

**Comment by orionr** [comment]
Looks like we got ENOMEM=12 on that last run, so retesting.

**Comment by orionr** [comment]
@caffe2bot retest this please

**Comment by houseroad** [comment]
@caffe2bot retest this please

**Review by pjh5 — APPROVED** [review]

**Comment by orionr** [comment]
@caffe2bot retest this please

**Comment by orionr** [comment]
Landing this since we're investigating test failures separately.

**Pull request merged**
