### PR TITLE
Add /usr/local/opt/python/libexec/bin to $PATH on Mac travis

### PR DESCRIPTION
**Pull request by Maratyszcza**
This should Travis the build failures on Mac

### CODE REVIEW

**Comment by bddppq** [comment]
I think we also need to
- do `brew install python` (or maybe even more explicit `brew install python==2.7.14`) in install.sh
- add `$(python $ROOT_DIR/scripts/get_python_cmake_flags.py)` to CMAKE_ARGS in build.sh

**Comment by Maratyszcza** [comment]
Do you suggest to always add `$(python $ROOT_DIR/scripts/get_python_cmake_flags.py)` to CMAKE_ARGS? Or only on OSX?

**Comment by bddppq** [comment]
Always. That script always finds include dir (which has portable logic) and only finds libpython on darwin platform.

**Comment by bddppq** [comment]
Hmm brew install doesn't support `==` syntax for specifying version.

**Comment by Maratyszcza** [comment]
Oops. It already landed internally, and will be pushed to GH soon

**Comment by bddppq** [comment]
Well it was broken before, we have not made it worse ;)

**Pull request closed without merging**
