### PR TITLE
Conda packaging for caffe2.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by Yangqing** [comment]
Super, thanks Edward :) I assume this is already verified in conda? If so I'll go ahead and merge it.

(the contbuild failure is a separate issue that we should have addressed)

**Comment by yapus** [comment]
I've just tried to build this branch in conda 4.3.22 under Mac OS X 10.12.6, Cuda 9.0.103, CudNN-9.0 osx-x64-v7 and I get the following errors:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory(2577): error: calling a __host__ function("std::__1::__compressed_pair< ::cub::CachingDeviceAllocator *,  ::std::__1::default_delete< ::cub::CachingDeviceAllocator> > ::__compressed_pair") from a __device__ function("std::__1::unique_ptr< ::cub::CachingDeviceAllocator,  ::std::__1::default_delete< ::cub::CachingDeviceAllocator> > ::unique_ptr") is not allowed

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory(2577): error: identifier "std::__1::__compressed_pair< ::cub::CachingDeviceAllocator *,  ::std::__1::default_delete< ::cub::CachingDeviceAllocator> > ::__compressed_pair" is undefined in device code
```

**Comment by Yangqing** [comment]
Interesting error from cuda - @yapus could you kindly let me know which file is causing the error?

cc @slayton58  FYI

**Comment by yapus** [comment]
Sorry, wrong thread, i moved my comment to #853​

**Comment by ezyang** [comment]
@Yangqing I verified that it builds in one particular conda configuration, but I can't vouch for it working in all circumstances (e.g., OS X). Given more time I can test more of these configs.

**Comment by Yangqing** [comment]
Thanks @ezyang - will merge.

**Pull request closed without merging**
