### PR TITLE
adding const fxn modifier to Operator::type()

### PR DESCRIPTION
**Pull request by Swetko**
First PR, small fix to Operator class interface.

### CODE REVIEW

**Comment by yinghai** [comment]
@caffe2bot retest this please

**Review by yinghai — COMMENTED** [review]
Thanks for doing this! Looks good. Let's wait until the tests are finished.

**Comment by yinghai** [comment]
@onnxbot test this please

**Comment by Swetko** [comment]
Hi! One of the checks fails: "continuous-integration/appveyor/pr — AppVeyor build failed" Not sure what's going on there. This should be a trivial change. Just testing how the whole process works. I have more stuff to commit later!

**Comment by bddppq** [comment]
@caffe2bot test this please

**Comment by bddppq** [comment]
@Swetko The appveyor CI is being deprecated, @pjh5 has migrated our windows CI to our Jenkins CI infra, so we can ignore the appveyor failure.

**Review by bddppq — APPROVED** [review]

**Pull request merged**
