### PR TITLE
Update CMake min requirement to 3, and use interface library for cuda libs.

### PR DESCRIPTION
**Pull request by Yangqing**
Firing a diff to see if this actually works across platforms.

### CODE REVIEW

**Comment by Yangqing** [comment]
Interesting finding. This only works with cmake3 because INTERFACE library is not available in 2.8.

**Comment by Yangqing** [comment]
@pietern Maybe we should enforce cmake 3 :)

**Review by pjh5 — APPROVED** [review]

**Comment by Yangqing** [comment]
@caffe2bot retest this please.

**Comment by Yangqing** [comment]
Ubuntu cmake3 install is pending a docker build trigger. Rest is passing properly (per centos7 build).

**Comment by pietern** [comment]
:heart:

**Pull request merged**
