### PR TITLE
Fix potential GPU transform OOB access

### PR DESCRIPTION
**Pull request by slayton58**
Occurred when running with multiple GPUs, not all of which
are connected via P2P.

Essentially when mean_gpu_ and std_gpu_ are allocated and
populated in the constructor of ImageInputOp, it does not seem to
be guaranteed that the active context is the same as the final context
on which the Op will be run. This causes the image data and the
mean/std to be on different devices. With P2P we don't mind this, but
without this causes OOB memory accesses in the GPU transform
kernel.

### CODE REVIEW

**Comment by slayton58** [comment]
@Yangqing for review

**Comment by akyrola** [comment]
Indeed, I don't think the GPU id is set when calling oeprator constructors.

**Comment by akyrola** [comment]
Hmm, actually operator.h will set the device (context_.SwitchToDevice) at constructor. Let me say why ImageInputOp doesn't do it

**Comment by akyrola** [comment]
it is because ImageINputOp does not inherit Operator, but OperatorBase via PrefetchOperator, and neither of those will call SwitchDevice()

**Comment by slayton58** [comment]
Ahhh, good catch! Which is easier, changing ImageInputOp to inherit from Operator, or my fix?

**Comment by akyrola** [comment]
Well I landed your fix already, I think it is fine. Actually I dislike doing data copy / computation in constructor anyway. But I am submitting diff to also fix the PrefetchOperator, as it can be used by other ops as well.

**Pull request closed without merging**
