### PR TITLE
[cmake] Move nnpack to modern cmake and avoid using EXTERNAL_DEPENDENCIES.

### PR DESCRIPTION
**Pull request by Yangqing**

### CODE REVIEW

**Comment by Maratyszcza** [comment]
Removing EXTERNAL_DEPENDENCIES looks good, but removing `if(NOT TARGET nnpack)` check does not. It is needed to avoid double-importing NNPACK when Caffe2 is built from within another project via `add_subdirectory`

**Comment by Yangqing** [comment]
@Maratyszcza good point. Reverted the change to nnpack.cmake.

**Review by Maratyszcza — APPROVED** [review]
LGTM

**Comment by Yangqing** [comment]
Thanks - merged to #2045.

**Comment by alphilly2013** [comment]
X

**Pull request closed without merging**
