### PR TITLE
Enable python3 builds

### PR DESCRIPTION
**Pull request by Yangqing**

### CODE REVIEW

**Comment by Yangqing** [comment]
(tested with a 3.6 anaconda build. Old behavior: found mismatching pythoninterp and pythonlib settings. New behavior: they match.)

**Comment by bddppq** [comment]
This is great. In onnx-caffe2 Python3 builds I had to detect the python include directory and libpython path and pass them to cmake.
https://github.com/onnx/onnx-caffe2/blob/master/.travis/build.sh#L38

**Comment by Yangqing** [comment]
Yeah, also a shout-out to @ilkarman for noticing the python3 build being tricky in his deep learning framework example repo.

**Comment by Yangqing** [comment]
Shoot, travis-ci seems to have an interesting failure, reverting for now.

**Pull request closed without merging**
