### PR TITLE
Added CMake changes to support ROCm

### PR DESCRIPTION
**Pull request by aditya4d**
1. Added changes to CMake to work on ROCm
2. Added AMD copyright.

### CODE REVIEW

**Comment by Yangqing** [comment]
This looks good - do you mind also setting up a Travis CI target?

**Comment by aditya4d** [comment]
MIOpen is not released yet, once it gets released, I'll change Travis build files to get required rocm packages.

**Comment by Yangqing** [comment]
Got it, thanks - importing.

**Comment by Yangqing** [comment]
@adityaatluri - I sent an email follow-up about the CLA logistics, could you ping me again when it is figured out?

**Comment by aditya4d** [comment]
Sure.

**Comment by orionr** [comment]
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

**Pull request closed without merging**
