### PR TITLE
Check if system has protobuf package when it already has protoc command

### PR DESCRIPTION
**Pull request by dzyong**
When system has protobuf package but hasn't protoc, cmake will be success:

> -- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-967-g27d12d8-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
...

Then make will be failed.
This submit make it to check protobuf package only when protoc has been found.

### CODE REVIEW

**Comment by pietern** [comment]
Nice catch! 

@caffe2bot test this please

**Comment by dzyong** [comment]
There are two test failed.
Both of them are failed at:

> self = <caffe2.python.operator_test.ngram_ops_test.TestNGramOps testMethod=test_ngram_from_categorical_op>
...
(mismatch 10.0%)
x: array([68, 12, 50, 59, 65, 33, 16, 28,  0, 51, 65, 28, 34, 16, 56, 10, 56,
             8, 32, 74])
y: array([68,  0, 50, 59, 65, 33, 16, 16,  0, 51, 65, 28, 34, 16, 56, 10, 56,
             8, 32, 74], dtype=int32)
...

I think this error shouldn't caused by this submit.

**Comment by dzyong** [comment]
These error seem has some relationship with this submit, but I'm not sure:
[add NGramFromCategorical Op](https://github.com/caffe2/caffe2/commit/6a938bb2dad1359dc5eb5a060946e93be79a9e40)

**Comment by dzyong** [comment]
@caffe2bot test this please

**Comment by dzyong** [comment]
Hi @pietern , I updated my forked branch with the official master branch, please help me to trigger @caffe2bot again.
Thanks.

**Comment by pietern** [comment]
@dzyong Thanks for the update. You don't need to create a new pull request for updates -- you can force push to the same branch to update an existing pull request.

**Pull request closed without merging**
