### PR TITLE
Use ccache for macOS builds if present

### PR DESCRIPTION
**Pull request by pietern**

### CODE REVIEW

**Comment by pietern** [comment]
Needs https://github.com/Yangqing/ios-cmake/pull/1 for the iOS build to use ccache.

**Comment by pietern** [comment]
@caffe2bot retest this please

**Comment by Yangqing** [comment]
Merged https://github.com/Yangqing/ios-cmake/pull/1 , this also LGTM, feel free to proceed :)

**Review by Yangqing — APPROVED** [review]

**Comment by pietern** [comment]
@Yangqing This doesn't include the bump yet.

**Comment by pietern** [comment]
Thanks @Yangqing! We raced on the bump ;)

**Pull request closed without merging**
