### PR TITLE
Fix CUDA check for gcc > 5.

### PR DESCRIPTION
**Pull request by hgaiser**
In response to https://github.com/caffe2/caffe2/pull/504 , this PR modifies the gcc compiler check for CUDA slightly. All ABI since [gcc-3](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) are compatible with eachother. The check from https://github.com/caffe2/caffe2/pull/504 forced the 'regular' CXX / CC compiler to be set to gcc < 6 but this is not required.

According to the documentation for [FindCUDA](https://cmake.org/cmake/help/v3.0/module/FindCUDA.html), `CUDA_HOST_COMPILER` is set to `CMAKE_C_COMPILER` by default. This PR checks if `CMAKE_C_COMPILER` is too new for CUDA 8 and whether `CUDA_HOST_COMPILER` is set to `CMAKE_C_COMPILER`. It also modifies the message slightly.

### CODE REVIEW

**Comment by hgaiser** [comment]
@pietern can you give feedback on this?

**Comment by Yangqing** [comment]
Also cc'ing @slayton58 - Simon, what is the recommended way from NVidia about setting host compiler in cmake?

**Comment by slayton58** [comment]
Either using `-DCUDA_HOST_COMPILER=<compiler>` or manually setting `-ccbin=<compiler>` in `CUDA_NVCC_FLAGS` is fine, no preference from us :)

**Comment by hgaiser** [comment]
@Yangqing can this then be merged?

**Pull request closed without merging**
