### PR TITLE
Move onnx-caffe2 inside caffe2

### PR DESCRIPTION
**Pull request by yinghai**
This PR moves all the python source code from https://github.com/onnx/onnx-caffe2 to caffe2. It helps stage follow-up PRs to have C++ onnx-caffe2 backend and control the size of the diff.  There will a couple of PRs after this one:
- Pull onnx into third-party and cmake support
- C++ onnx-caffe2 backend with Python wrapper to replace majority functions of the backend.py.

### CODE REVIEW

**Comment by bddppq** [comment]
@caffe2bot test this please

**Comment by bddppq** [comment]
@yinghai Is this a straightforward copy?

**Comment by yinghai** [comment]
It's not because I have to change the module name since the path has changed. 
`onnx_caffe2.*` -> `caffe2.python.onnx_caffe2.*`

**Comment by yinghai** [comment]
OK. Build failed because of dependency on `onnx` and `psutil`. Will update.

**Comment by bddppq** [comment]
Makes senses. The tests are failing (expected since onnx submodule is not added yet.), you need to modify https://github.com/caffe2/caffe2/blob/master/.jenkins/test.sh to ignore the onnx_caffe2 tests for now.

**Comment by yinghai** [comment]
I'm thinking the reverse, updating the test env to make it work.

**Comment by dzhulgakov** [comment]
Nice! maybe make the namespace a bit easier? The whole `caffe2.python` is already a bit weird. One option would be to just make it `caffe2.onnx` similarly to `pytorch.onnx` (you could probably remap the modules in cmake or just keep it `caffe2.python.onnx` if it's too hard)

**Comment by yinghai** [comment]
By renaming `onnx_caffe2` folder to `onnx`, we can naturally have `caffe2.python.onnx` as module name. I'll do that.

**Comment by yinghai** [comment]
@bddppq  It's still not picking up the module. Do we need to rebuild docker image manually?

**Comment by bddppq** [comment]
@caffe2bot retest this please

**Comment by bddppq** [comment]
@caffe2bot retest this please

**Comment by yinghai** [comment]
@caffe2bot test this please

**Review by bddppq — APPROVED** [review]
Tests are passing now. Awesome!

**Pull request merged**
