### PR TITLE
gemm: fp16 tensorcore fixes

### PR DESCRIPTION
**Pull request by lukeyeager**

### CODE REVIEW

**Comment by akyrola** [comment]
This one is over one month old, is it still relevant?

**Comment by lukeyeager** [comment]
Yes. I'm surprised nobody has complained about these issues yet. Presumably y'all don't run any tensorcore tests on non-Volta hardware.

**Comment by akyrola** [comment]
Ok, processing it. Thanks!

**Comment by orionr** [comment]
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

**Pull request closed without merging**
