### PR TITLE
fp16 support for NCCL ops

### PR DESCRIPTION
**Pull request by slayton58**
fp16 dispatch for NCCL

### CODE REVIEW

**Comment by Yangqing** [comment]
This looks great to me, cc'ing @pietern for a final look and approval.

**Comment by pietern** [comment]
Looks great to me as well.

Minor nit: AllInputsAreFloat is a perfect use case for template<T> AllInputsAre ;)

Good to merge as is though.

**Comment by slayton58** [comment]
@pietern Good point :) give me a couple of minutes to fix it

**Comment by slayton58** [comment]
@pietern Done.

**Comment by pietern** [comment]
Awesome, thanks @slayton58!

**Review by pietern — APPROVED** [review]

**Pull request closed without merging**
