### PR TITLE
Fix BAD_PARAM errors

### PR DESCRIPTION
**Pull request by slayton58**

### CODE REVIEW

**Comment by Yangqing** [comment]
@slayton58 could you do a rebase? :)

**Comment by slayton58** [comment]
@Yangqing I'm out today, so I can't do it until Monday. It should, however, be a trivial rebase, so it might be easiest if someone else brings in my branch and does it themselves.

**Comment by slayton58** [comment]
@Yangqing Rebased.

**Comment by pietern** [comment]
@slayton58 Thanks!

**Comment by prigoyal** [comment]
@slayton58 can you rebase this PR again? the travis build failure is due to an issue in trunk and it was fixed a while ago.

**Pull request closed without merging**
