### PR TITLE
Update caffe_translator.py

### PR DESCRIPTION
**Pull request by ezineo**
Add "PReLU" TranslatorRegistry in caffe_translator.py

### CODE REVIEW

**Comment by bwasti** [comment]
would you mind splitting out the BatchNorm changes into a different pull request?

**Review by bwasti — CHANGES_REQUESTED** [review]
Thanks! Please separate the BatchNorm change into a different pull request.

**Comment by ezineo** [comment]
There are still some problems. The BatchNorm in Caffe must follow with a Scale layer, so that it can be equal to Caffe2's implementation.

**Comment by ezineo** [comment]
OK, I see...

**Pull request closed without merging**
