### PR TITLE
Fix build_ios.sh bug (#194) due to name collision.

### PR DESCRIPTION
**Pull request by nicodjimenez**

### CODE REVIEW

**Comment by Yangqing** [comment]
Thanks so much!

cc @wickedfoo - Jeff, would this affect your local changes?

**Comment by wickedfoo** [comment]
@Yangqing This should be fine, if I attempt to compile again at some point, the compiler will complain and I can fix.

**Comment by wickedfoo** [comment]
This doesn't look like the threadpool I wrote in any case?

**Comment by Yangqing** [comment]
@wickedfoo Ah yeah, you are right, this is from @bwasti and is probably a contribution from our friend @slayton58 :) Looks safe.

**Comment by slayton58** [comment]
Yes, this looks like mine :) It's used to provide threaded decode / transform in the ImageInputOp

**Pull request closed without merging**
